apiVersion: v1
kind: Secret
metadata:
  name: fluentd-secret-@#env#@
  namespace: kube-system 
type: Opaque
data:
  FLUENT_ELASTICSEARCH_PASSWORD: @#fluentdpassword#@
  FLUENT_ELASTICSEARCH_USER: @#fluentduser#@
