---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-@#env#@
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    app.kubernetes.io/name: fluentd-@#env#@
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/part-of: logging

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd-@#env#@
rules:
  - apiGroups: [""]
    resources:
      - pods
      - events
      - persistentvolumeclaims
      - secrets
      - services
      - configmaps
      - daemonsets
      - namespaces
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-@#env#@
roleRef:
  kind: ClusterRole
  name: fluentd-@#env#@
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: fluentd-@#env#@
    namespace: kube-system

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-@#env#@
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    app.kubernetes.io/name: fluentd-@#env#@
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/part-of: logging
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      app.kubernetes.io/name: fluentd-@#env#@
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        app.kubernetes.io/name: fluentd-@#env#@
        app.kubernetes.io/version: "1.0"
        app.kubernetes.io/part-of: logging
    spec:
      serviceAccountName: fluentd-@#env#@
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: environment
                    operator: In
                    values:
                      - @#env#@
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      @#imgpull#@
      containers:
        - name: fluentd
          image: @#acr#@.azurecr.io/fluentd-kubernetes-daemonset:v1-debian-elasticsearch
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: FLUENT_ELASTICSEARCH_HOST
              value: "es-es-http.elastic-system.svc.cluster.local"
            - name: FLUENT_ELASTICSEARCH_PORT
              value: "9200"
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: "https"
            - name: FLUENT_UID
              value: "0"
            - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
              value: "false"
            - name: FLUENT_ELASTICSEARCH_SSL_VERSION
              value: "TLSv1_2"
            - name: FLUENT_ELASTICSEARCH_USER
              valueFrom:
                secretKeyRef:
                  name: fluentd-secret-@#env#@
                  key: FLUENT_ELASTICSEARCH_USER
            - name: FLUENT_ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fluentd-secret-@#env#@
                  key: FLUENT_ELASTICSEARCH_PASSWORD
            - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
              value: /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/
            - name: FLUENT_CONTAINER_TAIL_EXCLUDE_PATH
              value: >
                [
                  "/var/log/containers/fluent*",
                  "/var/log/containers/calico-*",
                  ...
                ]
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: fluentd-@#env#@
              mountPath: /fluentd/etc/conf.d/custom.conf
              subPath: fluent.conf
              readOnly: true
            - name: varlog
              mountPath: /var/log
            - name: dockercontainerlogdirectory
              mountPath: /var/log/containers
              readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: fluentd-@#env#@
          configMap:
            name: fluentd-config
            items:
              - key: fluent.conf
                path: fluent.conf
        - name: varlog
          hostPath:
            path: /var/log
        - name: dockercontainerlogdirectory
          hostPath:
            path: /var/log/containers
