apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-@#env#@
  namespace: @#ns#@
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: "grafana-@#env#@"
spec:
  accessModes:
  - ReadWriteMany
  reclaimPolicy: Retain
  storageClassName: @#sc#@
  resources:
    requests:
      storage: 50Gi
