apiVersion: v1
kind: Service
metadata:
  name: grafana-@#env#@
  namespace: @#ns#@
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: "grafana-@#env#@"
spec:
  selector: 
    app: grafana-@#env#@
  type: ClusterIP  
  ports:
    - port: 3000
      targetPort: 3000
