apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmqcluster
  namespace: @#ns#@
  labels:
    app.kubernetes.io/name: "rabbitmq"
    app.kubernetes.io/instance: "rabbitmqcluster"
    app.kubernetes.io/part-of: "messaging"
    app.kubernetes.io/version: "3.10"
spec:
  replicas: 1
  image: @#acr#@.azurecr.io/rabbitmq:3.10-management
  @#imgpull#@
  service:
    type: ClusterIP
  persistence:
    storageClassName: @#sc#@
    storage: 100Gi
  resources:
    requests:
      cpu: 2000m
      memory: 4Gi
    limits:
      cpu: 6000m
      memory: 12Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nodeType
            operator: In
            values:
            - general
            key: environment
            operator: In
            values:
            - @#env#@
  rabbitmq:
    envConfig: |
      CONFIG_FILE=/usr/local/etc/rabbitmq/rabbitmq
