apiVersion: v1
kind: Namespace
metadata:
  name: nttool
  labels:
    name: nttool
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-tester
  namespace: nttool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-tester
  template:
    metadata:
      labels:
        app: network-tester
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodeType
                operator: In
                values:
                - compute
      containers:
      - image: @#image#@
        imagePullPolicy: IfNotPresent
        name: network-tester
